name: drivn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  pinput: ^3.0.1
  intl_phone_number_input: ^0.7.3+1
  file_picker: ^6.1.1
  # flutter_typeahead: ^5.0.1
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  page_transition: ^2.0.9
  dartz: ^0.10.1
  http: ^1.1.0
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  audioplayers: ^5.1.0
  get_it: ^7.6.4
  loading_animation_widget: ^1.2.0+4
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  flutter_appauth: ^6.0.2
  google_sign_in: ^6.1.5
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  permission_handler: ^11.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/  

  fonts:
      - family: SwitchIcon
        fonts:
          - asset: fonts/SwitchIcon.ttf
  
      - family: Inter
        fonts:
          - asset: fonts/Inter-VariableFont_slnt_wght.ttf
