/// Flutter icons SwitchIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
// /    - family:  SwitchIcon
// /      fonts:
// /       - asset: fonts/SwitchIcon.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SwitchIcon {
  SwitchIcon._();

  static const _kFontFam = 'SwitchIcon';
  static const String? _kFontPkg = null;

  static const IconData toggle_off = IconData(0xf204, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_on = IconData(0xf205, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
